services:
  wordpress:
    image: 'wordpress:latest'
    volumes:
      - 'wordpress-files:/var/www/html'
    environment:
      - 'SERVICE_FQDN_WORDPRESS=https://testingwordpress14.pxxl.pro'
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=a4755e09960014d1852af7ae406066b7
      - WORDPRESS_DB_NAME=wordpress
      - COOLIFY_RESOURCE_UUID=3f0686d893ed47cbb6ac34f60a
      - COOLIFY_CONTAINER_NAME=wordpress-3f0686d893ed47cbb6ac34f60a
      - 'COOLIFY_URL=https://testingwordpress14.pxxl.pro'
      - COOLIFY_FQDN=testingwordpress14.pxxl.pro
    command: >
      bash -c "echo 'ServerName wordpresssite.pxxl.pro' >> /etc/apache2/apache2.conf &&
               docker-entrypoint.sh apache2-foreground"
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1g
        reservations:
          cpus: '0.4'
          memory: 512m
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1'
      interval: 2s
      timeout: 10s
      retries: 10

  mysql:
    image: 'mysql:8'
    volumes:
      - 'mysql-data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=5e11b4c28da44aa19b8545ed0861793d
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=a4755e09960014d1852af7ae406066b7
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 512m
        reservations:
          cpus: '0.2'
          memory: 256m
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - 127.0.0.1
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  wordpress-files:
  mysql-data:
